// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton'];
  const ElCard: typeof import('element-plus/es')['ElCard'];
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox'];
  const ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup'];
  const ElCol: typeof import('element-plus/es')['ElCol'];
  const ElCollapse: typeof import('element-plus/es')['ElCollapse'];
  const ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem'];
  const ElContainer: typeof import('element-plus/es')['ElContainer'];
  const ElDialog: typeof import('element-plus/es')['ElDialog'];
  const ElFooter: typeof import('element-plus/es')['ElFooter'];
  const ElHeader: typeof import('element-plus/es')['ElHeader'];
  const ElIcon: typeof import('element-plus/es')['ElIcon'];
  const ElImage: typeof import('element-plus/es')['ElImage'];
  const ElInputNumber: typeof import('element-plus/es')['ElInputNumber'];
  const ElMain: typeof import('element-plus/es')['ElMain'];
  const ElMenu: typeof import('element-plus/es')['ElMenu'];
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
  const ElRow: typeof import('element-plus/es')['ElRow'];
}
export {};
