// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Createuser.body': typeof import('./src/components/createuser/createuser.body.vue')['default']
    'Createuser.form': typeof import('./src/components/createuser/createuser.form.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    'Header.bodt': typeof import('./src/components/share/header.bodt.vue')['default']
    Menubody: typeof import('./src/components/menu/menubody.vue')['default']
    Menuprodpop: typeof import('./src/components/menu/menuprodpop.vue')['default']
    MenuTable: typeof import('./src/components/menu/menuTable.vue')['default']
    Tempbody: typeof import('./src/components/deprecated/tempandhumidity/tempbody.vue')['default']
    Weatherbody: typeof import('./src/components/deprecated/weather/weatherbody.vue')['default']
  }
}

export { }
