// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'Createuser.body': typeof import('./src/components/createuser/createuser.body.vue')['default']
    'Createuser.form': typeof import('./src/components/createuser/createuser.form.vue')['default']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    'Header.bodt': typeof import('./src/components/share/header.bodt.vue')['default']
    MenuFBbody: typeof import('./src/components/menuFB/menuFBbody.vue')['default']
    MenuFBTable: typeof import('./src/components/menuFB/menuFBTable.vue')['default']
    OrderSection: typeof import('./src/components/menuFB/orderSection.vue')['default']
    Tempbody: typeof import('./src/components/tempandhumidity/tempbody.vue')['default']
    Weatherbody: typeof import('./src/components/weather/weatherbody.vue')['default']
  }
}

export { }
