version: "3.9"

services:
  onlinemenu_vite_vue:
    container_name: onlinemenu_vue
    image: thelittlesheep/onlinemenu_vue:dev
    ports:
      - 3001:3001
    volumes:
        - ./frontend:/usr/src/app
    restart: unless-stopped
  onlinemenu_nestjs:
    container_name: onlinemenu_nestjs
    image: thelittlesheep/onlinemenu_nestjs:dev
    command: yarn start:debug
    ports:
        - 3000:3000
        - 9229:9229 # for vscode debug
    volumes:
        - ./backend:/usr/src/app
    restart: unless-stopped
  onlinemenu_redis:
    container_name: onlinemenu_redis
    image: redis:alpine
    ports:
      - 6379:6379
    restart: unless-stopped


networks:
  default:
    name: web_service